In [27]:
import numpy as np



In [11]:
x=18.55845
np.floor(x), np.ceil(x), np.round(x),


(18.0, 19.0, 19.0)

In [25]:
np.deg2rad(x)

0.32390605656674165

In [23]:
d=np.array( [ [ [1,2] , [3,4] ] ,[ [5,6] , [7,8] ] ] )
print(d.ndim)
print(d[0][0][1])

3
2


In [39]:
np.random.randint(low=0, high=5,size=10)

array([0, 1, 2, 0, 4, 1, 1, 4, 3, 1])

In [42]:
list(range(0,12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [43]:
[*range(12)] 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [2]:
name='ahmed'
age=22

print(f"may name is {name} and my age is {age}")

may name is ahmed and my age is 22


In [3]:
np.random.randint(low=1, high=10, size=(5,6))

array([[9, 8, 4, 6, 2, 9],
       [3, 5, 3, 5, 2, 3],
       [8, 1, 7, 4, 4, 3],
       [1, 6, 9, 6, 9, 6],
       [6, 6, 6, 9, 4, 2]])

In [4]:
e=np.random.uniform(low=0, high=6, size=10000)
e

array([1.6064635 , 4.28267662, 1.93563299, ..., 5.99354032, 4.87192806,
       1.18438039])

In [5]:
np.random.randint(1,50,(5,5))

array([[12, 21, 24, 49, 32],
       [39, 28, 21, 45, 23],
       [10,  5, 27, 21, 19],
       [10, 34,  3, 48, 18],
       [23, 34, 26, 42, 23]])

In [2]:
arr = np.arange(0,11)

In [3]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
slice_of_arr = arr[1:6]
slice_of_arr

array([1, 2, 3, 4, 5])

In [7]:
slice_of_arr[:]=50
slice_of_arr

array([50, 50, 50, 50, 50])

In [8]:
arr


array([ 0, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [11]:
arr_2d=np.array( ([ [1,8,2] , [3,8,4]  , [5,5,6] , [7,8,2] ] ))
arr_2d

array([[1, 8, 2],
       [3, 8, 4],
       [5, 5, 6],
       [7, 8, 2]])

In [14]:
slice_2d = arr_2d[0:3 , 1:3]
slice_2d

array([[8, 2],
       [8, 4],
       [5, 6]])

In [15]:
arr_2d


array([[1, 8, 2],
       [3, 8, 4],
       [5, 5, 6],
       [7, 8, 2]])

In [17]:
print(arr_2d)
print('-'*30)
print(arr_2d.sum(axis=None))

[[1 8 2]
 [3 8 4]
 [5 5 6]
 [7 8 2]]
------------------------------
59


                                                          if the value of axis=0  => return the sum of each column

In [18]:
print(arr_2d)
print('-'*30)
print(arr_2d.sum(axis=0))

[[1 8 2]
 [3 8 4]
 [5 5 6]
 [7 8 2]]
------------------------------
[16 29 14]


                                                               if the value of axis=1  => return the sum of each row

In [19]:
print(arr_2d)
print('-'*30)
print(arr_2d.sum(axis=1))

[[1 8 2]
 [3 8 4]
 [5 5 6]
 [7 8 2]]
------------------------------
[11 15 16 17]


In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [24]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [25]:
np.random.randint(0,8,(3,3))

array([[0, 0, 5],
       [0, 4, 2],
       [3, 7, 4]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.random(25)

array([0.95405799, 0.72928145, 0.83818293, 0.21217336, 0.93410531,
       0.831319  , 0.8893302 , 0.96707483, 0.09793489, 0.40313807,
       0.66850583, 0.73509444, 0.32564294, 0.62858895, 0.5899622 ,
       0.02944071, 0.99189429, 0.22486686, 0.94413464, 0.25708939,
       0.73565859, 0.45070945, 0.61937452, 0.50966401, 0.2086918 ])

In [34]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [36]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [38]:
ar = np.arange(1,26).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
ar_slice = ar[2: ,1: ]
ar_slice

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [45]:
ar.std()

7.211102550927978

In [47]:
ar.sum()

325

In [49]:
ar.sum(axis=0)

array([55, 60, 65, 70, 75])

In [50]:
ar.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [32]:
import numpy as np
from numpy.random import randn

In [21]:
import pandas as pd

In [16]:
labels=['a','b','c','d','e']
my_list=[10,20,30,40,50]
arr = np.array(my_list)
d = {'a':10,'b':20,'c':30}

In [11]:
pd.Series(data=my_list , index=labels)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [12]:
pd.Series(arr)

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [13]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [3]:
np.random.seed(101)

In [34]:
df = pd.DataFrame(data=np.random.randn(5,4) , index=['A','B','C','D','E'], columns=['W','X','Y','Z'])
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [35]:
df[['W','Y']]

W         Y
A  0.302665 -1.706086
B -0.134841  0.166905
C  0.807706  0.638787
D -0.497104 -0.943406
E -0.116773  0.238127

In [36]:
df['New'] = df['W'] + df['Z']

In [37]:
df

W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119 -0.856454
B -0.134841  0.390528  0.166905  0.184502  0.049661
C  0.807706  0.072960  0.638787  0.329646  1.137352
D -0.497104 -0.754070 -0.943406  0.484752 -0.012352
E -0.116773  1.901755  0.238127  1.996652  1.879879

                                                       to delete an column in dataframe you must make axis = 1

In [38]:
df.drop('New' , axis = 1)

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [39]:
df

W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119 -0.856454
B -0.134841  0.390528  0.166905  0.184502  0.049661
C  0.807706  0.072960  0.638787  0.329646  1.137352
D -0.497104 -0.754070 -0.943406  0.484752 -0.012352
E -0.116773  1.901755  0.238127  1.996652  1.879879

In [40]:
df.drop('New', axis = 1 , inplace = True)

In [41]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

                                                                    to select row

In [19]:
df.loc['A']

W    0.386030
X    2.084019
Y   -0.376519
Z    0.230336
Name: A, dtype: float64

In [21]:
df.iloc[3]

W   -1.382920
X    1.482495
Y    0.961458
Z   -2.141212
Name: D, dtype: float64

In [25]:
df.loc['A':'C']

W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845

                select dataframe by index
            select the values of x that mapped to values > 0 in Z

In [42]:
 df[df['Z']>0]['X']

B    0.390528
C    0.072960
D   -0.754070
E    1.901755
Name: X, dtype: float64

            select dataframe where values of W > 0 and values of Y < 0

In [30]:
df[(df['W']>0) & (df['Y']<0)]

W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
E  0.992573  1.192241 -1.046780  1.292765

In [31]:
df[(df['W']>0) | (df['X']<0)]

W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
E  0.992573  1.192241 -1.046780  1.292765

In [32]:
df.reset_index(inplace = False)

index         W         X         Y         Z
0     A  0.386030  2.084019 -0.376519  0.230336
1     B  0.681209  1.035125 -0.031160  1.939932
2     C -1.005187 -0.741790  0.187125 -0.732845
3     D -1.382920  1.482495  0.961458 -2.141212
4     E  0.992573  1.192241 -1.046780  1.292765

                    add new column

In [33]:
new_id= 'CA NY WY CO LA'.split()

In [34]:
new_id

['CA', 'NY', 'WY', 'CO', 'LA']

In [36]:
df['States'] = new_id

In [37]:
df

W         X         Y         Z States
A  0.386030  2.084019 -0.376519  0.230336     CA
B  0.681209  1.035125 -0.031160  1.939932     NY
C -1.005187 -0.741790  0.187125 -0.732845     WY
D -1.382920  1.482495  0.961458 -2.141212     CO
E  0.992573  1.192241 -1.046780  1.292765     LA

                    add new row

In [40]:
df.loc['NewRow'] = [1,2,3,4,'BV']

In [41]:
df

W         X         Y         Z States
A       0.386030  2.084019 -0.376519  0.230336     CA
B       0.681209  1.035125 -0.031160  1.939932     NY
C      -1.005187 -0.741790  0.187125 -0.732845     WY
D      -1.382920  1.482495  0.961458 -2.141212     CO
E       0.992573  1.192241 -1.046780  1.292765     LA
NewRow  1.000000  2.000000  3.000000  4.000000     BV

In [38]:
df.set_index('States', inplace = False)

W         X         Y         Z
States                                        
CA      0.386030  2.084019 -0.376519  0.230336
NY      0.681209  1.035125 -0.031160  1.939932
WY     -1.005187 -0.741790  0.187125 -0.732845
CO     -1.382920  1.482495  0.961458 -2.141212
LA      0.992573  1.192241 -1.046780  1.292765

In [39]:
df

W         X         Y         Z States
A  0.386030  2.084019 -0.376519  0.230336     CA
B  0.681209  1.035125 -0.031160  1.939932     NY
C -1.005187 -0.741790  0.187125 -0.732845     WY
D -1.382920  1.482495  0.961458 -2.141212     CO
E  0.992573  1.192241 -1.046780  1.292765     LA

In [63]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [66]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [67]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [68]:
df = pd.DataFrame(data = np.random.randn(6,2),index = hier_index,columns = ['A','B'] )
df

A         B
G1 1  0.392489  0.221491
   2 -0.855196  1.541990
   3  0.666319 -0.538235
G2 1 -0.568581  1.407338
   2  0.641806 -0.905100
   3 -0.391157  1.028293

In [69]:
df.loc['G1']

A         B
1  0.392489  0.221491
2 -0.855196  1.541990
3  0.666319 -0.538235

In [73]:
df.loc['G1'].loc[1]

A    0.392489
B    0.221491
Name: 1, dtype: float64

In [74]:
df.index.names

FrozenList([None, None])

In [75]:
df.index.names = ['Group' , 'num']  #naming the indexes 

In [82]:
df.xs(1 , level= 'Num') #return the first row from two groups

A         B
Group                    
G1     0.392489  0.221491
G2    -0.568581  1.407338

                           # Pandas-Missing Data

In [1]:
import pandas as pd
import numpy as np

In [84]:
df = pd.DataFrame(
           { 
            'A':[1,2,np.nan],
            'B':[5,np.nan,np.nan],
            'C':[1,2,3]   
           }
)

In [85]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [86]:
df.dropna()        #drop any row that contain null 

A    B  C
0  1.0  5.0  1

In [87]:
df.dropna(axis = 1) #drop any column that contain null 

C
0  1
1  2
2  3

In [88]:
df.dropna(thresh=2) #delete the row that contain 2 null

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [93]:
df.fillna(value = 'VALUE')   #fill the null with real value

A      B  C
0    1.0    5.0  1
1    2.0  VALUE  2
2  VALUE  VALUE  3

#                       Pandas Group-By

In [98]:
Data = {
    'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
    'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
    'Sales':[200,120,340,124,243,350]  
}

In [99]:
df = pd.DataFrame(data = Data )

In [100]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [102]:
byCompany = df.groupby('Company')

#                 return the mean of all sales 

In [104]:
byCompany.mean()     

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

#            return the sum of sales in each company

In [105]:
byCompany.sum()  

Sales
Company       
FB         593
GOOG       320
MSFT       464

#              return the sum of sales for FB company

In [106]:
byCompany.sum().loc['FB']   

Sales    593
Name: FB, dtype: int64

#             return all the statitics of the company

In [107]:
byCompany.describe()   

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

#        Pandas - Merging,Joining,and Concatenating

In [2]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']},
    index = [0,1,2,3]
)

In [3]:
df2 = pd.DataFrame({
    'A':['A4','A5','A6','A7'],
    'B':['B4','B5','B6','B7'],
    'C':['C4','C5','C6','C7'],
    'D':['D4','D5','D6','D7']},
    index = [4,5,6,7]
)

In [4]:
df3 = pd.DataFrame({
    'A':['A8','A9','A10','A11'],
    'B':['B8','B9','B10','B11'],
    'C':['C8','C9','C10','C11'],
    'D':['D8','D9','D10','D11']},
    index = [8,9,10,11]
)

#         Concatenation

In [7]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#               Merging       ->  merge on columns

In [9]:
left = pd.DataFrame({
    'key':['k0','k1','k2','k3'],
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3']  
})

In [10]:
right = pd.DataFrame({
    'key':['k0','k1','k2','k3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']  
})

In [13]:
pd.merge(left,right, how = 'inner' , on = 'key')

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [15]:
left1 = pd.DataFrame({
    'key1':['k0','k1','k2','k3'],
    'key2':['k0','k1','k0','k1'],
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3']  
})


right1 = pd.DataFrame({
    'key1':['k0','k1','k2','k3'],
    'key2':['k0','k1','k0','k1'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']  
})

In [18]:
pd.merge(left1,right1, how= 'outer' , on = ['key1','key2'])

key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k1  A1  B1  C1  D1
2   k2   k0  A2  B2  C2  D2
3   k3   k1  A3  B3  C3  D3

#                     Join   -> join on index

In [19]:
left2 = pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3']},
     index = ['k0','k1','k2','k3']
)


right2 = pd.DataFrame({
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']},
     index = ['k4','k5','k6','k7']
)

In [24]:
left2.join(right2 , how = 'outer')

A    B    C    D
k0   A0   B0  NaN  NaN
k1   A1   B1  NaN  NaN
k2   A2   B2  NaN  NaN
k3   A3   B3  NaN  NaN
k4  NaN  NaN   C0   D0
k5  NaN  NaN   C1   D1
k6  NaN  NaN   C2   D2
k7  NaN  NaN   C3   D3

#                         Pandas operation

In [25]:
df = pd.DataFrame({
    'col1':[1,2,3,4],
    'col2':[444,555,666,444],
    'col3':['abc','def','ghi','xyz']})

In [26]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

#      get unique values

In [29]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

#        get the num of unique values

In [33]:
df['col2'].value_counts()

3

#        How many times the value appear?

In [32]:
df['col2'].value_counts()

444    2
666    1
555    1
Name: col2, dtype: int64

#         apply a function on the DataFrame

In [35]:
def times2(x):
    return x*2

In [36]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [38]:
df['col2'].apply(lambda x:x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [39]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

#                 Pandas Input and Output

##         Read the data from csv file

In [9]:
df = pd.read_csv('data/breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

##     Write the data to new csv file

In [12]:
df.to_csv('newData.csv')

In [13]:
pd.read_csv('newData.csv')

Unnamed: 0        id diagnosis  radius_mean  texture_mean  \
0             0    842302         M        17.99         10.38   
1             1    842517         M        20.57         17.77   
2             2  84300903         M        19.69         21.25   
3             3  84348301         M        11.42         20.38   
4             4  84358402         M        20.29         14.34   
..          ...       ...       ...          ...           ...   
564         564    926424         M        21.56         22.39   
565         565    926682         M        20.13         28.25   
566         566    926954         M        16.60         28.08   
567         567    927241         M        20.60         29.33   
568         568     92751         B         7.76         24.54   

     perimeter_mean  area_mean  smoothness_mean  compactness_mean  \
0            122.80     1001.0          0.11840           0.27760   
1            132.90     1326.0          0.08474           0.07864   
2            130.00     1203.0          0.10960           0.15990   
3             77.58      386.1          0.14250           0.28390   
4            135.10     1297.0          0.10030           0.13280   
..              ...        ...              ...               ...   
564          142.00     1479.0          0.11100           0.11590   
565          131.20     1261.0          0.09780           0.10340   
566          108.30      858.1          0.08455           0.10230   
567          140.10     1265.0          0.11780           0.27700   
568           47.92      181.0          0.05263           0.04362   

     concavity_mean  ...  texture_worst  perimeter_worst  area_worst  \
0           0.30010  ...          17.33           184.60      2019.0   
1           0.08690  ...          23.41           158.80      1956.0   
2           0.19740  ...          25.53           152.50      1709.0   
3           0.24140  ...          26.50            98.87       567.7   
4           0.19800  ...          16.67           152.20      1575.0   
..              ...  ...            ...              ...         ...   
564         0.24390  ...          26.40           166.10      2027.0   
565         0.14400  ...          38.25           155.00      1731.0   
566         0.09251  ...          34.12           126.70      1124.0   
567         0.35140  ...          39.42           184.60      1821.0   
568         0.00000  ...          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  \
0                  0.2654          0.4601                  0.11890   
1                  0.1860          0.2750                  0.08902   
2                  0.2430          0.3613                  0.08758   
3                  0.2575          0.6638                  0.17300   
4                  0.1625          0.2364                  0.07678   
..                    ...             ...                      ...   
564                0.2216          0.2060                  0.07115   
565                0.1628          0.2572                  0.06637   
566                0.1418          0.2218                  0.07820   
567                0.2650          0.4087                  0.12400   
568            